### ISSUE TITLE
Inicializace reakčních experimentů

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#105]
- Reakční experimenty zatím nebudeme řešit ohledně zpětné vazby, je potřeba udělat nejdříve jejich konfiguraci
- Byl bych hodně rád kdyby se podařilo dodržet inline vzhled všech prvků např ve screenu "NASTAVENÍ 1" by prvních pět parametrů mělo mít popisek zarovnaný doleva a nastavovací inputy by měli být zarovnány doprava, pokud to bude veliký problém nezbývá to udělat tak jako vždy a popisky budou nad inputy

![img_20160404_203141_hdr](https://cloud.githubusercontent.com/assets/13770080/14259229/4690069a-faa6-11e5-8efd-22ef8380eb56.jpg)

**Comment by stechy1** [comment]
Co je zač ta první kontrolka v nastavení 2?

**Comment by Vrbikk** [comment]
výběr z nabídky

**Comment by Vrbikk** [comment]
tlačítka uložit hodnoty by měli být zase dole podle našeho standardu :D

**Comment by stechy1** [comment]
Ony někde nejsou dole?

**Comment by Vrbikk** [comment]
já jen, že tyto návrhy jsem kreslil, když si říkal že bude problém je dát dolů, ale teď už víme že to je v pohodě

**Comment by Vrbikk** [comment]
hotovo
