### ISSUE TITLE
c-VEP - vylepšení layoutu

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#106]
1) parametr Bitový posun předělat na nový number Spinner a umístit jej jako druhý v pořadí (pod počet výstupů)

2) Díky úspoře místa považuji za lepší umístit 32 - bit pattern na druhý screen (vše na jednom místě), protože samotný 32 bit pattern nevypadá osamoceně moc dobře

**Comment by stechy1** [comment]
O tom patternu si ještě popovídáme...

**Comment by Vrbikk** [comment]
domluvili jsme se že pattern zůstane na stejném místě, ale přidělá se mu popisek

**Comment by stechy1** [comment]
Jaký popisek?

**Comment by Vrbikk** [comment]
něco jako "Pattern 32 bit:"

**Comment by Vrbikk** [comment]
v pořádku, úpravy vzhledu budou v #109
