### ISSUE TITLE
Zachování hodnot po natočení zařízení 

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#107]
některé hodnoty se nezachovají a patterny se bugnou, až spadne aplikace 

je potřeba vyřešit způsob uchování dat při natoceni a to I všech screenu

**Comment by Vrbikk** [comment]
zatím není potřeba řešit hezké rozvržení na šířku ale vyřešit pouze správnou funkčnost

**Comment by Vrbikk** [comment]
ještě to nefunguje u ERP - nastavení parametrů

**Comment by stechy1** [comment]
Co přesně nefunguje?

**Comment by Vrbikk** [comment]
uchování hodnot při natočení

**Comment by stechy1** [comment]
To mas na mysli hodnoty, které zadas, ale neulozis?

**Comment by Vrbikk** [comment]
jo přesně, ono jak je to proměnlivé vzhledem k parametru tak to bude asi problém že?
všude jinde to funguje dobře až na tyhle parametrové věcí

**Comment by stechy1** [comment]
To bych musel řešit jiným způsobem. Ale da se to vyřešit...

**Comment by Vrbikk** [comment]
zatím to nebude nutné, v pohodě
