### ISSUE TITLE
Navrhnout nové rozložení prvků napříč celou aplikací

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#109]
- začnlenit novou položku výběru číselné hodnoty do starého layoutu
- optimalizovat přehlednost a vzhled

**Comment by Zuzacek** [comment]
![12939696_10205472932213985_1164987136_n](https://cloud.githubusercontent.com/assets/17786783/14325551/2418740a-fc2a-11e5-963e-69561f16ed2f.jpg)
![12966330_10205472933654021_1360101767_n](https://cloud.githubusercontent.com/assets/17786783/14325552/24338a60-fc2a-11e5-89ff-6f85353ef211.jpg)
![12969413_10205472935094057_1696551936_n](https://cloud.githubusercontent.com/assets/17786783/14325553/244126ac-fc2a-11e5-9e34-9e9e036fc3b4.jpg)
![12980637_10205472935974079_1217532242_n](https://cloud.githubusercontent.com/assets/17786783/14325554/24420126-fc2a-11e5-9a92-248091d46711.jpg)

**Comment by Zuzacek** [comment]
![12980637_10205472935974079_1217532242_n](https://cloud.githubusercontent.com/assets/17786783/14325830/6daeda68-fc2b-11e5-8388-df00cb4dea50.jpg)
![12939696_10205472932213985_1164987136_n](https://cloud.githubusercontent.com/assets/17786783/14325829/6dae6c4a-fc2b-11e5-8c8e-3859969d2739.jpg)
![12966330_10205472933654021_1360101767_n](https://cloud.githubusercontent.com/assets/17786783/14325832/6db1589c-fc2b-11e5-86dc-09eee5722892.jpg)
![12969413_10205472935094057_1696551936_n](https://cloud.githubusercontent.com/assets/17786783/14325831/6db09b3c-fc2b-11e5-91d9-8a67ca0283aa.jpg)

**Comment by stechy1** [comment]
No tak to si pěkně naložím :D

**Comment by Vrbikk** [comment]
Máš design od profesionála :dancer:

**Comment by Vrbikk** [comment]
Předávám návrhy na Petra

**Comment by Vrbikk** [comment]
aha ono už toje... takže předělám jen labely :dango:

**Comment by Vrbikk** [comment]
jen upozorním, že v t-VEP je stále bugnuté tlačítko "uložit vše", ale v c-VEP funguje dobře, mělo by se to opravit v rámci redesignu

**Comment by stechy1** [comment]
Jo, moje blbost...

**Comment by Vrbikk** [comment]
![screenshot_2016-04-06-21-37-02_cz zcu fav tymsnu stimulatorremotecontrol](https://cloud.githubusercontent.com/assets/13770080/14330667/e16e3a14-fc41-11e5-8cac-620c4b7ff336.png)

**Comment by Vrbikk** [comment]
hotovo
