### ISSUE TITLE
ošklivé zobrazení t-VEP patternů, pokud není vybraná žádná konfigurace

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#112]
když nezvolíme žádnou konfiguraci, nejsou odkryty žádné bity patternů, nevypadá to moc dobře, a stejně jako u c-VEP by bylo dobré zobrazit v této situaci všechny bity patternů

toto issue je opravdu jen libůstka, prio:low

![screenshot_2016-04-06-21-44-20_cz zcu fav tymsnu stimulatorremotecontrol](https://cloud.githubusercontent.com/assets/13770080/14330819/9e61e364-fc42-11e5-81a9-ecd2eb99d377.png)

**Comment by stechy1** [comment]
To spis nezobrazit žádné a dat tam hlášku něco ve smyslu vyberte konfiguraci...

**Comment by Vrbikk** [comment]
to by bylo taky dobré řešení, ale spíše bych to vyplnil plnými patterny, protože pak vyvstává otázka, že vlastně bez výběru konfigurace by neměl uživatel vůbec přístup do nastavení u všech experimentů

**Comment by Vrbikk** [comment]
vyřešeno
