### ISSUE TITLE
Omezit délku názvu konfigurace a názvu duplikované konfigurace + regulární výraz

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#113]
- omezení by mělo být asi 32 znaků 
- po překročení by měl být vyhozen **Snackbar** jako vždy
- součástí by měla být ochrana proti všem znakům co není písmeno nebo číslo a "_"

**Comment by stechy1** [comment]
Přidám podporu ověření názvu konfigurace, kterou načítám ze souboru. Může se totiž stát, že někdo ten soubor přejmenuje až po jeho vytvoření. Pokud bychom to neošetřili, tak aplikace bude padat. 
Navrhuji tedy udělat toto opatření a po přečtení všech patternů zobrazit **Snackbar** s informací o počtu (ne)úspěšně načtených konfigurací.

**Comment by Vrbikk** [comment]
Tak jo, budeš na tuhle funkci chtít další Issue?

**Comment by stechy1** [comment]
Asi není potřeba, implementuji to ještě tady...

**Comment by Vrbikk** [comment]
součástí tothoto issue je i jiné uspořádání složek konfigurace experimentů - aplikace nebude padat pokud bude nucena načíst špatnou konfiguraci

**Comment by Vrbikk** [comment]
Funkce funguje na výbornou, chválím použití **Toast**u na správném místě, tedy není ukončena editace názvu souboru
