### ISSUE TITLE
Nová organizace složek pro experimenty

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#115]
- je potřeba vytvořit pro každý experiment složku, která bude obsahovat konfigurační soubory
- součástí této implementace bude ochrana proti načtení potencionálně špatné konfigurace - aplikace nespadne, ale vyhodí upozornění na počet špatně načtených konfiguracích

**Comment by stechy1** [comment]
Jenom k těm složkám, je potřeba to upravit pouze pro ERP, protože všechny BCI experimenty už rozdělené jsou....

**Comment by Vrbikk** [comment]
dobrá práce
