### ISSUE TITLE
Prozkoumat možnosti retrofitu

### ISSUE THREAD

**Issue by stechy1** [stechy1/stimulatorremotecontrol#118]
Na stránce: [Retrofitu](https://futurestud.io/blog/retrofit-how-to-integrate-xml-converter) je tutoriál, kde ukazují možnosti, jak se má třída oanotovat, aby na ní mohl být použit **Retrofit**.
Pokud by se zdálo, že to usnadní práci, mohli bychom toto řešení implementovat místo dosavadního.

**Comment by stechy1** [comment]
Podporované formáty retrofitem: 
Gson: com.squareup.retrofit:converter-gson
Jackson: com.squareup.retrofit:converter-jackson
Moshi: com.squareup.retrofit:converter-moshi
Protobuf: com.squareup.retrofit:converter-protobuf
Wire: com.squareup.retrofit:converter-wire
Simple XML: com.squareup.retrofit:converter-simplexml

**Comment by Vrbikk** [comment]
podívám se na to

**Comment by Vrbikk** [comment]
implementace Retrofitu záležitostí další verze
