### ISSUE TITLE
Inicializace nápovědy pro aplikaci

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#122]
- nápověda by měla sloužit k orientace mezi parametry stimulací
- kategorie nápovědy budou právě typy stimulace
- obsah bude postupně doplněn, je ale důležité mít připravené rozhraní

**expandable listview** by mělo bohatě stačit:
![image](https://cloud.githubusercontent.com/assets/13770080/14408980/a4e2cefa-ff09-11e5-97b1-52963fe97e71.png)

do budoucna bych si představoval rozšíření této nápovědy taky o teoretické povídání o jednotlivých experimentech, nicméně to teď neřešíme

**Comment by stechy1** [comment]
Našel jsem zajímavou knihovnu, která dělá přesně to, co bychom potřebovali...
https://github.com/amlcurran/ShowcaseView

**Comment by Vrbikk** [comment]
nad tímhle jsem přemýšlel taky ale nezdá se mi to jako výhodné a strašně pracné, při každé změně by se to navíc muselo předělávat

**Comment by stechy1** [comment]
Tak to by se implementovalo az jako poslední fičůra

**Comment by Vrbikk** [comment]
stáhl jsem si jejich aplikaci vypadá to dobře, ale spíš jako průvodce ovládáním aplikace...

**Comment by Vrbikk** [comment]
to by bylo vhodné např. při prvním otevření konfigurace, řeklo by to jaké tlačítko je jaké...

**Comment by stechy1** [comment]
Ano, na to je to dělané

**Comment by Vrbikk** [comment]
nejdříve uděláme tuhle hloupou nápovědu a potom by se mohl udělat ten tutoriál

**Comment by Vrbikk** [comment]
mechanicky to funguje výborně, jde jen o věci designu, chtěl bych:
- **rozlišit kategorii od položky** a to nejlépe tak, že by kategorie byla větším písmem a tučně a položky v ní by byly odsazené (celkově by to mělo být odsazené, ale položky v jednotlivých kategoriích více)
- taky by bylo fajn aby kategorie měli jednoduchý obrázek (všechny stejný), který by se měnil, jestli by kategorie byla rozkliklá nebo ne, což bude jednoduché na implementaci, ten obrázek by byla nejlepší vlevo

**Comment by Vrbikk** [comment]
ještě je třeba doplnit obsahy kategorií, které jsem připravil do strings

**Comment by stechy1** [comment]
Teď na to koukám, a máme tu menší zádrhel. Je sice pěkné, že jsi seskupil jednotlivé BCI popisi dohromady, ale já nemám možnost je spojit. Takhle bych musel udělat pro f-VEP, c-VEP a t-VEP samostatnou kategorii v menu nápovědy

**Comment by stechy1** [comment]
Nápovědu zobrazíme pomocí HTML, toto issue je zbytečné
