### ISSUE TITLE
REA - změna "Wait-random" a "Miss-time" nevyvolá stav "změněno" v konfiguraci

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#124]
po stisknutí "uložit hodnoty" tyto dva parametry také nevyhodí snackbar

**Comment by stechy1** [comment]
Ups, opravíme na přednášce :D

**Comment by Vrbikk** [comment]
zjistilo se, že chyba je mnohem více rozsáhlá

**Comment by Vrbikk** [comment]
vyřešeno, chybu způsobil Gradle
