### ISSUE TITLE
Otestovat všechny prvky aplikace v0.4.1

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#126]
Testování se bude týkat těchto experimentů: ERP a všechny BCI
1. vytvoří se konfigurace se všemi nastavenými parametry
2. zkontroluje se jejich správné uložení a načtení
3. následně bude několikrát duplikována, mazána a přejmenována

tento test by měl odhalit zda jsou data experimentů konzistentní a vše funguje jak má

**Comment by Vrbikk** [comment]
nově jdu otestovat ještě REA

**Comment by Vrbikk** [comment]
testování odhalilo několik závažných chyb (t-VEP)

**Comment by stechy1** [comment]
Testování odhalilo, že @Vrbikk programuje ve stylu CTRL+C, CTRL+V
