### ISSUE TITLE
t-VEP - špatný ukazatel "změněno"

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#129]
1. vytvoříme novou konfiguraci a upravíme v ní patterny, uložíme
2. založíme novou konfiguraci - nová konfigurace má automaticky značku změny

místo kroku 2. lze jen označit jinou konfiguraci a je ihned nastavená jako změněná

**Comment by stechy1** [comment]
Problém je v tom, že pattern kontrolka vyvolá změnu i když jí nechceme, jdu zjistit co s tím...

**Comment by Vrbikk** [comment]
vypadá to dobře, vyřešeno
