### ISSUE TITLE
REA - po načtení konfigurace (ze souboru) se nenačte počet výstupů

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#130]
tento problém se vyskytuje také při duplikování konfigurace, kde vše proběhne v pořádku, ale počet výstupů je vždy nastaven na hodnotu 1

**Comment by stechy1** [comment]
Špatně jsem otagoval commit. Řešení je v issue #129

**Comment by Vrbikk** [comment]
jdu to otestovat

**Comment by Vrbikk** [comment]
v pořádku, funguje to dobře
