### ISSUE TITLE
Lehký redesign REA

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#131]
- spinner pro "Počet výstupů" by měl být blíže popisku (stejně jako třeba t-VEP)
- "On fail" výběr by měl být ve stejném stylu jako třeba v ERP (alpha kanál)
- checkbox "F" bych dal více doleva, aby nerušil vzhled vzdálenost mezi M a F by měla být stejná jako právě jeden takový checkbox s jednopísmenným popiskem :)

**Comment by stechy1** [comment]
Můžeš 3. položku nějak vizualizovat?

**Comment by Vrbikk** [comment]
jdu na to :)

**Comment by Vrbikk** [comment]
![dero](https://cloud.githubusercontent.com/assets/13770080/14439860/ad6587fa-002d-11e6-8ee4-b636beaae6f8.png)

**Comment by Vrbikk** [comment]
v pořádku, ale pro jistotu to ještě necháme projet očima naší designérky @Zuzacek
