### ISSUE TITLE
Představa o vizualizaci - REA

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#132]
Napadlo mě:
- Bylo by potřeba nějak vyzualizovat reakční experimenty, ale nejspíš nebude BT
- Udělali bychom screen na kterém by byly dvě tlačíka "Správně" "Chybně" což by vlastně emulovalo packety, které by přicházeli do našeho Androidu (jen nevím jestli v těch packetech nebude rovnou čas té události, což nejspíš bude, napíšu mu email) 
- Přičemž bychom nad těmito tlačítky vizualizovali následující parametry
  - počet správně
  - počet špatně
  - průměrný čas reakce
  - poslední čas reakce
- Kromě těchto informací by se hodil graf těchto událostí v závislosti na rostoucím čase
- bylo by fajn se domluvit jak to udělat, abychom ukázali, že tuto poslední funkci máme implementovanou a připravenou

**Comment by stechy1** [comment]
Místo nového screenu s tlačítky, můžeme vytvořit vlastního klienta třeba v **C#**, kde bychom měli tyto tlačítka. Tím bychom mohli rovnou vyzkoušet tu BT komunikaci...

**Comment by Vrbikk** [comment]
návrh je zatím nepodstatný, nemáme podkladové materiály k vytvoření smysluplného odsimulování REA... bohužel
