### ISSUE TITLE
Najít způsob oddělení položek kategorie nápovědy

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#138]
- Je potřeba nějak oddělit položky v nápovědě, jelikož nemáme možnost formátování
- představoval bych si větší mezery (jen o trošku)
  ![screenshot_2016-04-15-22-22-11_cz zcu fav tymsnu stimulatorremotecontrol](https://cloud.githubusercontent.com/assets/13770080/14573913/9a463c7c-0358-11e6-85ca-4898b35603ab.png)
  větší mezery

**Comment by stechy1** [comment]
Mohly bychom se kompletně vykašlat na **expandable listView** a místo toho vytvořit nápovědu čistě v **HTML**, které zobrazíme v **HTML View**

**Comment by Vrbikk** [comment]
takhle klikatelný je to po kategoriích docela dobrý, udělat více HTML view pod kategorie by nešlo?

**Comment by stechy1** [comment]
To je blbost. Mnohem lepší na výkon je mít jedno HTML view a v něm mís statickou stránku

**Comment by stechy1** [comment]
Toto issue se může zavřít. Přišli jsme na lepší způsob, jak zobrazit nápovědu
