### ISSUE TITLE
Implementace kompletních Unit testů

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#145]
- nastudovat problemaiku Unit testů v androidu a vymyslet strukturu testů a kritické části aplikace

**Comment by stechy1** [comment]
Určitě budeme testovat tyto třídy:

## Konfigurace
- [x] AConfiguration
- [x] ERPConfiguration
- [x] FVEPConfiguration
- [x] CVEPConfiguration
- [x] TVEPConfiguration
- [x] REAConfiguration

## Správce konfigurací
- [ ] Manager

## Bajtové operace
- [x] Code
- [x] DataConvertor
- [x] Packet

## Utils
- [x] RangeUtils

**Comment by stechy1** [comment]
Na managera se podíváme až ve čtvrtek večer, musím zjistit, jak se testují generické třídy

**Comment by Vrbikk** [comment]
v pořádku
