### ISSUE TITLE
Testování UI

### ISSUE THREAD

**Issue by stechy1** [stechy1/stimulatorremotecontrol#160]
Začínáme testovat UI naší aplikace pomocí frameworku [espresso](http://developer.android.com/training/testing/ui-testing/espresso-testing.html).

**Comment by Vrbikk** [comment]
- Představoval bych si první testy, které budou jen umět procházet jednotlivé experimenty a kontrolovat, zda zde existují položky
- Dále pak mohou tyto testy sami vytvářet konfigurace a pracovat s nimi

nicméně už samotné procházení aplikací by bohatě stačilo

**Comment by stechy1** [comment]
Základní testování je v pořádku
