### ISSUE TITLE
Rozsahy hodnot

### ISSUE THREAD

**Issue by Zuzacek** [stechy1/stimulatorremotecontrol#168]
Píšu jen to co mi přijde zvláštní jo, nevím přesně, jak mají být ty rozsahy.
- [x] ERP - Obecné nastavení - rozsah Out a Wait, lze zadávat i záporná čísla
- [x] ERP - Nastavení výstupů - V typech parametru Pulse - up, Pulse - down a Distribution - delay lze zadat záporná čísla
- [x] f-VEP - Nastavení výstupů - V typech parametru Pulse - up, Pulse - down lze zadat záporná čísla
- [x] t-VEP - Obecné nastavení - Délka pulsu i časová mohou být záporná.
- [x] c-VEP - Obecné nastavení - Délka pulsu může být záporná.
- [x] REA - Nastavení 1 - Všemu až na Brightness [%] a počet výstupů lze nastavit záporná hodnota.
- [x] REA - Nastavení 2 - A, W a H mohou mít záporné hodnoty

**Comment by stechy1** [comment]
Teď mi padá aplikace, když zadám zápornou hodnotu, takže musím ještě ošetřit vstupy...

**Comment by Vrbikk** [comment]
hotovo
