### ISSUE TITLE
Vymyslet ikonu pro konfiguraci, kterou se nepodařilo načíst

### ISSUE THREAD

**Issue by stechy1** [stechy1/stimulatorremotecontrol#169]
Bude se jednat o tzv. corrupted file.
Nápady na obrázky přikládám v [zde](https://www.google.cz/search?q=corrupted+file+icon&rlz=1C1AVNE_enCZ676CZ676&tbs=isz:i,ic:gray&tbm=isch&source=lnt&sa=X&ved=0ahUKEwihrPGupr3MAhUjCsAKHUgwDukQpwUIEw&dpr=1&biw=1366&bih=667)

**Comment by Zuzacek** [comment]
![corrupted](https://cloud.githubusercontent.com/assets/17786783/15019311/d5d1843a-121d-11e6-9678-cee07a1c77c1.png)
Tuto je dobré? Jestli jo, tak ti to pošlu na slacku, jsem nejde nahrát to svg.

**Comment by stechy1** [comment]
Je to parádní

**Comment by stechy1** [comment]
![Takhle vypadá ikona v praxi](https://cloud.githubusercontent.com/assets/8261059/15021397/d4f82bbe-1226-11e6-883c-79c490aa8e71.png)

**Comment by Zuzacek** [comment]
![corrupted2](https://cloud.githubusercontent.com/assets/17786783/15083406/4dad963c-13cd-11e6-84bd-79af81d68413.png)

**Comment by Vrbikk** [comment]
implementováno ve verzi aplikace v1.0
