### ISSUE TITLE
Implementovat podporu opercí s .xml soubory u ERP schémat

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#19]

**Comment by stechy1** [comment]
Zápis do souboru je již hotový.

**Comment by stechy1** [comment]
Čtení ze souboru taky. Bohužel se nejedná o xml, protože to je prostě moc hardcore. Tak jsme se rozhodli o formát JSON.
V kódu zůstane podpora pouze pro zápis do XML, pokud bude potřeba, tak se může implementovat do rozhraní.
