### ISSUE TITLE
Inicializovat rozvržení BCI f-VEP

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#20]
po #45 se implementuje samotná funkce f-VEP

menu -> BCI -> f-VEP

f-VEP bude mít první tečku správa konfigurací, druhá tečka bude obsahovat počet výstupů/stimulů a třetí bude nastavovat parametry TIME ON, TIME OFF, FREQ, DUTY CYCLE, Jas.... stejně jako v ERP

![img_20160324_132335_hdr](https://cloud.githubusercontent.com/assets/13770080/14016942/cb627fb0-f1c3-11e5-883a-99100b76632d.jpg)

Parametry:
- Time ON (doba zapnutí výstupu) [ms]
- Time OFF(doba vypnutí výstupu) [ms]
- Frekvence (Frekvence) 0-255
- Duty cycle(nejspíš nastavení středu periody) 0-255
- Jas 0-100

**Comment by stechy1** [comment]
Nahraj mi sem i obrázky, jak by to mělo vypadat.

**Comment by Vrbikk** [comment]
upreveny podklady pro implementaci funkce

**Comment by stechy1** [comment]
Finální verze f-VEP
![fvep](https://cloud.githubusercontent.com/assets/8261059/14051699/4908dd5e-f2c5-11e5-9205-1440df38810b.png)

**Comment by Vrbikk** [comment]
funkce implementována, teď to musíme ještě odladit
