### ISSUE TITLE
Vytvořit Kontrolku reprezentující Pattern

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#21]
- od 1 do 32 bitů
- dobře klikatelná

přemýšlel jsem o nějakém poli checkboxů, ale to asi nebude to pravé

**Comment by stechy1** [comment]
Chtělo by to nějaké náčrtky, jak by měla vypadat. Návrh rozměrů + funkčnosti...

**Comment by stechy1** [comment]
Screenshot z první verze kontrolky.
Jak je vidět, je složena jednoduše z checkboxů. Když je šířka kontrolky větší, než je šířka obrazovky, tak se zobrazí horizontální scroll bar.
![screenshot_20160321-145614](https://cloud.githubusercontent.com/assets/8261059/13952467/d2c44d44-f036-11e5-8aed-b9a036b6b724.png)

**Comment by Vrbikk** [comment]
to vypadá dobře, šlo by při větším počtu udělat více řádků? např pro 8 bitů by došlo k "odřádkování"?

**Comment by stechy1** [comment]
Právě proto je tam ten posuvnik...

**Comment by Vrbikk** [comment]
posuvník není dobrý protože se snadno v tak velkém patternu ztratíš

**Comment by stechy1** [comment]
Když já nevím, jak bych udělal to zalamovani...

**Comment by Vrbikk** [comment]
není tam nějaký horizontal box? nebo tu kontrolku mít uvnitř tabulky a přidávat políčka... no nevím co třeba přidat popisky čísel bitů? to by částečně vyřešilo problém

**Comment by stechy1** [comment]
Už jsem něco našel. Flowlayout...

**Comment by Vrbikk** [comment]
vypadá to jinak dost dobře a ten Flowlayout ujde, zkus to s tím

**Comment by Vrbikk** [comment]
Vypadá to v pořádku
