### ISSUE TITLE
Zobrazit toast při uložení hodnot v ERP

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#27]
V druhé a třetí tečce zobrazit toast např (Uloženo do schema: xxx) nebo (není kam uložit / není zvoleno žádné schéma) 

důvod je takový že vlastně nevíme zda se něco událo

**Comment by stechy1** [comment]
Nějak nechápu, proč to zobrazovat do druhé a třetí tečky. Udělal jsem to tak, že prostě po kliknutí na uložit se zobrazí snackbar s hláškou, že uložení proběhlo v pořádku.

**Comment by Vrbikk** [comment]
Aha mě se to nezobrazuje... zítra mě s tím budeš muset naučit a taky mi nejde smazat schémata
