### ISSUE TITLE
Označené schéma v rámci ERP teček 

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#30]
Po stisknutí "vybrat" u schéma se označí v listview..... když někdo vyskočí z nabídky ERP provede se reset označení a po návratu se může označit a vybrat první ze seznamu

**Comment by stechy1** [comment]
Musí se označit a vybrat první? Nestačil by jenom reset označení a neoznačovat žádné schéma?

**Comment by Vrbikk** [comment]
Dobře tak to uděláme tak jak říkáš

**Comment by stechy1** [comment]
Pak to tedy zavřu, protože to je implementováno.
