### ISSUE TITLE
Smazání schémata

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#33]
nefunguje možnost smazat schéma v ERP

**Comment by stechy1** [comment]
Potýkám se při smazání schématu s jistým problémem.
Protože obrázek je více, než tisíc slov, tak ho přikládám:
![screenshot_20160322-162818](https://cloud.githubusercontent.com/assets/8261059/13957071/60229c4a-f04b-11e5-8f78-1a8f2d4769f6.png)
Toto se stane po smazání schématu a nevím, jak se toho zbavit :/

**Comment by stechy1** [comment]
Odstranil jsem pozadí vybrané položky a tedy i odstranil bug. Zavírám...
