### ISSUE TITLE
Předělat nadpis ERP schémat na počet schémat

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#35]
http://imgur.com/DiOQ7iZ

**Comment by stechy1** [comment]
Nepoužívej na obrázky službu třetích stran. Github je umí zobrazovat přímo...

**Comment by stechy1** [comment]
Je k tomu nějaký pádný důvod? Když bych to musel měnit, tak by to bylo hromada kódování navíc...

**Comment by Vrbikk** [comment]
Zavírám issue - nepotřebná funkce
