### ISSUE TITLE
Nová položka menu "O aplikaci" - nahrazuje defaultní layout "vyber z denní nabídky"

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#36]
Po studeném zapnutí aplikace skočí přímo na tuto obrazovku a také bude k nalezení pod položkou "nastavení" v menu

http://imgur.com/bvcTecM

**Comment by stechy1** [comment]
![screenshot_20160323-160812](https://cloud.githubusercontent.com/assets/8261059/13989615/7d989eca-f111-11e5-8cba-100f7a346583.png)
