### ISSUE TITLE
Prohození rozložení ERP položek

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#37]
1) Prohození druhé a třetí tečky (uživatel si nejdříve chce nastavit počet výstupů až potom param.)
2) V obecných nastavení bude lepší a rychlejší použít na počet výstupů kontrolku Spinner

**Comment by stechy1** [comment]
Takže toto issue už neplatí?

**Comment by stechy1** [comment]
**Spinner** to nebude, ta kontrolka se jmenuje **NumberPicker**. Můžu rovnou vyhodit i tlačítko _uložit_, protože jsem schopnej zachytit změnu hodnoty v **NumberPickeru**

**Comment by Vrbikk** [comment]
a zachytis i změnu třeba nabezny hrany?

**Comment by stechy1** [comment]
Jo, to už implementovaný je. To tlačítko bylo čistě kvůli tomu počtu výstupů

**Comment by Vrbikk** [comment]
v tom případě je to v pořádku

**Comment by stechy1** [comment]
Tak ten **NumberPicker** vypadá aktuálně takto:
![screenshot_20160322-180834](https://cloud.githubusercontent.com/assets/8261059/13960571/318fae82-f059-11e5-8b57-793740fae2f5.png)
Jen mám problém s vycentrováním textu, nebo máš lepší nápad, kam umístit nápis _Počet výstupů_?

**Comment by stechy1** [comment]
Souhlasíš s orientací toho **NumberPickeru**?
![screenshot_20160322-181302](https://cloud.githubusercontent.com/assets/8261059/13960732/d52d85d2-f059-11e5-8e1c-bb0821f3de21.png)

**Comment by stechy1** [comment]
Pokud nejsou výhrady k pozici **NumberPickeru**, tak se toto issue může zavřít

**Comment by Vrbikk** [comment]
Zavírám issue, podrobnosti jsme vyřešili osobně na UIR
