### ISSUE TITLE
Změna značení schémat nenačtené/načtené/vybrané

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#39]
![fotka_filipa_ve_sprse](https://cloud.githubusercontent.com/assets/13770080/13958854/f53ba37a-f051-11e5-8953-2ff26a6d5cea.jpg)

Nenačtené - bude nyní bez jakékoliv ikony ale s šedým textem (místo ikony je odsazení nebo prázdná bílá ikona)
Načtené - text schématu se ztmaví/zčerná
Vybrané - U schématu se objeví zatržená ikonka jako v posledním případě

Poslední změnou je přidávání schémat, podle Material Designu nesmí dva kulaté buttony být dole vedle sebe, tedy se přidávací tlačítko udělá přímo na první tečku ERP

**Comment by stechy1** [comment]
Je toto dostatečně uspokojivé?
![screenshot_20160324-113253](https://cloud.githubusercontent.com/assets/8261059/14014660/3da9de02-f1b4-11e5-8163-2b70d7c277c5.png)
Napadlo mě, že ty zaškrtávací checkboxy bych tam nechal. Vypadá to lépe, než když to tam neni

**Comment by stechy1** [comment]
![screenshot_20160324-114653](https://cloud.githubusercontent.com/assets/8261059/14014951/1f9da96e-f1b6-11e5-96d5-b175ee436a26.png)
