### ISSUE TITLE
Snackbar notifikace

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#44]
pro zlepšení interakce s uživatelem je potřeba vyhodit hlášku pokud:
- stiskne "uložit vše" (bylo zapsány do souboru schémata : x , y, z)
- stiskne "uložit hodnoty" (do schématu x byly uložené hodnoty)

**Comment by stechy1** [comment]
Nevím, jestli je dobré u _uložit vše_ vypisovat seznam všch schémat, která byla uložena

**Comment by stechy1** [comment]
Zase na druhou stranu, to bude asi mnohem používanější tlačítko, než přes kontextové menu :D

**Comment by Vrbikk** [comment]
dobře, pokud nebude problém vypsat seznam schémat, která se zapisují do souboru asi bych to nechal a možná funkci z kontextového menu by bylo možné odstranit

**Comment by stechy1** [comment]
Problém by to nebyl, jen by ten snackbar chvíli pěkně spamoval...

**Comment by Vrbikk** [comment]
tak to zatím udělej bez výpisu souborů, jen pokud všechny zápisy proběhnou v pořádku, tak vypiš uloženo do souboru a třeba počet zapsaných souborů...

**Comment by stechy1** [comment]
Jo, to bych mohl...
