### ISSUE TITLE
f-VEP - uložit vše místo počtu uložených souborů napíše jen $s

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#50]
![screenshot_2016-03-26-09-06-07_cz zcu fav tymsnu stimulatorremotecontrol](https://cloud.githubusercontent.com/assets/13770080/14059041/30284a1c-f334-11e5-92e4-bf8495840780.png)

**Comment by stechy1** [comment]
Tato chyba je na více místech. Viz uložení všech schémat...
