### ISSUE TITLE
Verze aplikace 0.3 není správně otagovaná 

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#51]
- aplikace nemá uvnitř napsáno verzi 0.3 a ani android při instalaci nedetekuje 0.3 ale stále 0.2
- opravit ve verzi 0.31 bugfix

**Comment by stechy1** [comment]
Opravuji na verzi v0.3. Až se vydá bugfix verze, tak tam bude hodnota v0.3.1
