### ISSUE TITLE
v ERP i f-VEP lze vytvořit schéma s prázdným názvem

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#52]
![screenshot_2016-03-26-09-19-15_cz zcu fav tymsnu stimulatorremotecontrol](https://cloud.githubusercontent.com/assets/13770080/14059043/40b3f516-f334-11e5-8634-e9db4cb4e903.png)

**Comment by stechy1** [comment]
Jaká má být reakce? Stačí, když se dialog zavře a na uživatele vykoukne _Snackbar_ s informací, že název obsahuje nepovolené znaky?

**Comment by stechy1** [comment]
Zatím to implementuji pouze v f-VEPu, protože v ERP se bude předělávat logika na pozadí

**Comment by Vrbikk** [comment]
v pořádku :dancer:
