### ISSUE TITLE
Zkontrolovat zda je text čitelný na záhlaví.

### ISSUE THREAD

**Issue by Zuzacek** [stechy1/stimulatorremotecontrol#58]
![zahlavi2](https://cloud.githubusercontent.com/assets/17786783/14059425/9f023a4a-f340-11e5-83a5-27696eb26200.png)

**Comment by stechy1** [comment]
Zde je výsledek.
![screenshot_20160326-113035](https://cloud.githubusercontent.com/assets/8261059/14059600/3a9c35aa-f346-11e5-9137-914ee5bd14e3.png)

Teď je na tobě Zuzko, abys posoudila, jestli je ten text dostatečně čitelný

**Comment by Zuzacek** [comment]
Mě se to líbí, co vám? Možná bych mohla dát tu druhou barvu ještě o trochu tmavší.

**Comment by stechy1** [comment]
Ty jsi ten grafik :D Já to posoudit nedokážu. Ještě, co na to řekne @Vrbikk

**Comment by Zuzacek** [comment]
![zahlavi21](https://cloud.githubusercontent.com/assets/17786783/14059667/f4eeec2a-f348-11e5-86d7-1c7053a335a3.png)
Nebo ještě takhle a dát na to tmavý text.

**Comment by stechy1** [comment]
![screenshot_20160326-115646](https://cloud.githubusercontent.com/assets/8261059/14059680/d8afa508-f349-11e5-8524-f138577a5a4d.png)

**Comment by Zuzacek** [comment]
To se mi líbí víc. Co vám?

**Comment by stechy1** [comment]
Fajn, necháme tohle.

**Comment by stechy1** [comment]
Jestli to @Vrbikk schválí, můžeme zavřít.

**Comment by Zuzacek** [comment]
![zahlavi22](https://cloud.githubusercontent.com/assets/17786783/14060008/d51ad5c8-f355-11e5-8276-769fa7aad9eb.png)
Nebo tam můžu ještě dát takhle průhlednost.

**Comment by stechy1** [comment]
To taky nevypadá špatně

**Comment by Vrbikk** [comment]
mě se to líbí

**Comment by Zuzacek** [comment]
Super, tak já to uzavřu tedy jo

**Comment by Vrbikk** [comment]
jojo můžeš

**Comment by stechy1** [comment]
Počkej, ta průhlednost tam ještě neni

**Comment by Vrbikk** [comment]
v dalším release 0.3.+ bych si představoval tento průhledný obrázek od zuzky společně s vycentrovanými nápisy v černé barvě a bude to úplně suprový!, dobrá práce @Zuzacek jsi dobrá designérka :)

**Comment by stechy1** [comment]
![screenshot_20160327-210212](https://cloud.githubusercontent.com/assets/8261059/14067189/389e4814-f45f-11e5-8a99-1fb8f34dda7c.png)

**Comment by stechy1** [comment]
![screenshot_20160327-211853](https://cloud.githubusercontent.com/assets/8261059/14067271/8bc8f9ec-f461-11e5-9306-eb67cd4a3f11.png)

**Comment by Vrbikk** [comment]
v pohodě
