### ISSUE TITLE
Implementace ukazatele změny načtené konfigurace

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#62]
Položka v seznamu konfigurací by měla mít ukazatel toho, že není uložená do souboru, nejlépe ikonka v pravé části položky, ale může to být vyřešeno i jinak

jinak: nebylo by možné do souboru ukládat pokaždé? při změně počtu výstupů nebo při uložení parametrů? dost by to usnadnilo práci s aplikací a nemusel by člověk pořád myslet na ukládání

**Comment by Vrbikk** [comment]
zároveň by ve screenu s parametry mohlo být pouze tlačítko "ulož do + název konfigurace "

**Comment by stechy1** [comment]
Zatím bych nechal uložení na uživateli. Pokud by to byl problém, tak se automatické ukládání může doimplementovat.

**Comment by stechy1** [comment]
Jak by měl vypadat ukazatel změny?

**Comment by Vrbikk** [comment]
představoval bych si ikonku diskety na pravé straně položky pokud by to šlo

**Comment by stechy1** [comment]
Dobře

**Comment by Vrbikk** [comment]
dobrá práce, vypadá to dobře
