### ISSUE TITLE
Inicializovat c-VEP rozhraní

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#64]
![img_20160327_215223_hdr](https://cloud.githubusercontent.com/assets/13770080/14067561/581e6298-f467-11e5-9808-568fa56b1417.jpg)
- je nutné mít #21 
- c-VEP experimenty neobsahují žádné nastavení individuálních výstupů
- hodnoty z patternu se uloží jako bity do Intu a na základě kolik bude stimulů dojde k bitovým posunům  celého patternu (o kolik bitů ještě nevíme)
- tedy: screen "Nastavení" platí pro všechny výstupy a v konfiguračním souboru budou tyto hodnoty jen jednou a pattern tam bude tolikrát, kolik je nastavených stimulů

**Comment by stechy1** [comment]
Proč je ten obrázek obráceně?

**Comment by Vrbikk** [comment]
upraveno :dancers:

**Comment by Vrbikk** [comment]
třetí screen při zobrazení na šířku nemusí dělat extra úpravy, možná by to mohla být matice 2x16 co myslíš?

**Comment by stechy1** [comment]
Jo, s tím se počítá. Když se to bude vejít, tak žádná minimalizace se konat nebude.

**Comment by Vrbikk** [comment]
minimalizovat budem tey jen patterny, které budou na ten f-VEP když jich tam bude třeba 8 16bitových pod sebou...

**Comment by stechy1** [comment]
A tady se to teda minimalizovat nebude? To jako ze budu muset dělat dvě různé kontrolky?

**Comment by Vrbikk** [comment]
udělal bych jednu kontrolku, která bude pracovat v módu 8 na řádek nebo 16 na řádek.... ze začátku bych se spokojil i se statickou kontrolkou co umí jen řádkovat po osmi

**Comment by Vrbikk** [comment]
SKEW víme, že je nyní počet bitů 1-8 pro cyklický bitový posun.... může být řešeno spinnerem

**Comment by Vrbikk** [comment]
Struktura konfiguračního souboru

obecné:
- počet stimulů [1-8]
- délka pulsu "LENGHT" [ms]
- bitový posun "SKEW" [1-8 bitů]
- jas "BRIGHTNESS" [%]

array:
- počet stimulů \* 32bit pattern
  (první je originální Pattern, další patterny jsou posouvané o SKEW cyklicky,
  Pattern je typovaný jako int)

**Comment by Vrbikk** [comment]
po domluvě upravena struktura souboru jen na uložení jednoho patternu

**Comment by stechy1** [comment]
![cvep](https://cloud.githubusercontent.com/assets/8261059/14225423/b8aa39ca-f8c2-11e5-9abd-15e2d1cca624.png)

**Comment by Vrbikk** [comment]
malé úpravy

Obecná nastavení
- label "Počet výstupů" by měl být zarovnaný s tím number pickerem (s tím aktuálně vybraným číslem)
- nastavit levé a pravé odsazení všech elementů (klidně 1 cm na displeji od krajů)
- tlačítko "Uložit hodnoty" vycentrovat a nastavit mu nový android vzhled

Nastavení výstupů
- odsadit odshora 0,5 cm

jinak dobrý

**Comment by Vrbikk** [comment]
implementováno v pořádku
