### ISSUE TITLE
Implementace posuvníků u "Brightness" položek (ERP, f-VEP)

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#66]
- u jasu je hodnota jasná 0-100%, bylo by dobré tuto hodnotu nastavit pomocí posuvníků, ideální by byla kontrolka s posuvníkem a textovým polem, které by zobrazovalo hodnotu (vše v jedné řádce) 
- klidně mi sem napiš zda by to šlo a s jakým úsilím implementovat

**Comment by stechy1** [comment]
Bylo by to sice pěkný, ale Ja ty vstupy generují automaticky podle počtu výstupů a nemůžu rozlišovat, jestli náhodou nejsem na brightness abych tam dal nějaká šoupátka

**Comment by Vrbikk** [comment]
ok, aspoň že máme ty konfigurace a nebude se muset tak často psát, tak mě napadá co kdybychom přidali funkci na duplikování konfigurací?

**Comment by Vrbikk** [comment]
zavírám - nedá se dobře implementovat do stávajícího návrhu
