### ISSUE TITLE
Nové rozvržení konfigurací

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#68]
Pokud je více změněných konfigurací FAB zakrývá ikonu změny a po položení na šířku tlačítka "nová konfigurace" a "uložit vše" zbytečně zabírají místo pro náhled další položky konfigurace

napadlo mě tedy jiné rozvržení, které už počítá s FAB pro zastavení stimulace (vím že to je v rozporu s MD - mít dvě FAB vedle sebe, ale zatím nemám jiný návrh a pokud tyto tlačítka budou na jednom screenu, potom by to asi neměl být problém)

myslím že by to byl čistší návrh a nebyl by žádný problém s překrýváním prvků, navíc bychom ukázali naší schopnost dělat chytrý design 

![img_20160328_115233_hdr](https://cloud.githubusercontent.com/assets/13770080/14075799/8d72830a-f4dc-11e5-99d0-be43b0256197.jpg)

**Comment by stechy1** [comment]
Tak to už rovnou můžeme udělat 4 tlačítka vedle sebe. Třeba jim dat jenom obrázky.

**Comment by Vrbikk** [comment]
Přidávám vylepšené rozvržení pro layout konfigurace 
![img_20160329_160357_hdr](https://cloud.githubusercontent.com/assets/13770080/14110732/128eac26-f5c8-11e5-9fdb-8c0e20a41453.jpg)

**Comment by stechy1** [comment]
Tak všechno funguje až na jednu drobnost. Když změním orientaci telefonu portrait na landscape, tak se vzhled neupraví. Zatím nevím, jak to vyřešit

**Comment by stechy1** [comment]
Tak zatím to vypadá takhle
![responsivescreen](https://cloud.githubusercontent.com/assets/8261059/14115114/fba1cd4c-f5d9-11e5-8e29-bb0f9bb8c567.png)

Trošku mě trápí ta zelená čárka při landscape zobrazení

**Comment by Vrbikk** [comment]
v pořádku, ale nesmíme zapomenout vyřešit ty malé bugy
