### ISSUE TITLE
ERP - landscape - špatné zobrazení Obecného nastevní

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#69]
počet výstupů je moc nízko a není vidět, je třeba upravit rozložení prvků na šířku aby se nemuselo sjíždět dolů 
![screenshot_20160328-120856](https://cloud.githubusercontent.com/assets/13770080/14076072/cf2f0276-f4de-11e5-9afc-e3d9aaa7a73e.png)

**Comment by stechy1** [comment]
Není co řešit. Je tam **scrollView**, kterým lze posouvat obsah.
V budoucnu se budou tyto screeny redesignovat tak, abychom se vyhnuli podobné situaci

**Comment by Vrbikk** [comment]
jo dobře
