### ISSUE TITLE
Ukládání do nové konfigurace s def. počtem výstupů (4)

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#73]
Když se vytvoří nová konfigurace a přejde se na třetí screen v ERP, po uložení hodnot se kromě prvního políčka nic jiného neuloží (u f-VEP tento problém není), je to nejspíš pozůstatek z defaultního počtu výstupů 1

![screenshot_2016-03-28-19-15-03_cz zcu fav tymsnu stimulatorremotecontrol](https://cloud.githubusercontent.com/assets/13770080/14084810/e5872150-f51c-11e5-8e14-9885fcff01c4.png)

**Comment by stechy1** [comment]
U f-VEP byl problém také zjištěn. Stačí nastavit dvě po sobě jdoucí hodnoty (třeba 2. a 3. stimul) a uloží se pouze 2. ale třetí už ne.

**Comment by Vrbikk** [comment]
jdu to otestovat

**Comment by Vrbikk** [comment]
v pořádku
