### ISSUE TITLE
Označení schématu

### ISSUE THREAD

**Issue by stechy1** [stechy1/stimulatorremotecontrol#8]
Označit vybrané schéma při přechodu z jiného screenu.
![screenshot_20160312-140102 1](https://cloud.githubusercontent.com/assets/8261059/13723126/44575d22-e85b-11e5-86ae-531d6b8c8549.png)

**Comment by Vrbikk** [comment]
Budeme tedy toto implementovat? 

ještě by šlo po odchodu z ERP voleb resetovat neuložené hodnoty tak, jako když se zapne aplikace, tím bychom toto mohli zavřít

**Comment by stechy1** [comment]
Asi se na to vykašlem.

**Comment by Vrbikk** [comment]
Dobřa takže zavírám a budeme počítat s tím, že označeníá vybraného schématu bude jen lokálně v nastavení ERP a když se vyskočí do jiného menu bude to zresetovaný a bude se muset znovu načíst
