### ISSUE TITLE
ERP - parametr "Brightness" upravit pro sdružení 45 a 67

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#82]
je potřeba přepsat Labely

VÝSTUP:4 -> VÝSTUP:45
VÝSTUP:6 -> VÝSTUP:67

a zrušit 

VÝSTUP:5
VÝSTUP:7

model je nastavený a jas u těchto zrušených ze strany bajtů ignoruje, je potřeba vyřešit co se uloží do souborů s 5 a 7... asi 0

**Comment by Vrbikk** [comment]
hotovo

**Comment by stechy1** [comment]
Názvy asi přepsat nedokážu, ale můžu inputy nezobrazit

**Comment by stechy1** [comment]
Bohužel po důkladném zvážení musím konstatovat, že pro zachování jednoduchosti se tato featura implementovat nedá. Do dokumentace napíšeme, že hodnota v políčku 5 a 7 pro _brightness_ bude ignorována.

**Comment by Vrbikk** [comment]
dobře
