### ISSUE TITLE
Implemenentovat novou ikonku "uložit vše" pro konfigurační screeeny

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#85]
![ulo__itv__e_360](https://cloud.githubusercontent.com/assets/13770080/14170340/78ff2524-f72d-11e5-82f7-4719b6a56a62.png)

**Comment by stechy1** [comment]
Šlo by udělat tu druhou disketu světlejší? Když na to koukáme v mobilu, tak tam není vidět pomalu žádnej rozdíl.
![screenshot_20160331-134452](https://cloud.githubusercontent.com/assets/8261059/14174746/d50296ee-f746-11e5-8bb1-250e2fe440e0.png)

**Comment by Zuzacek** [comment]
![ulozitvse](https://cloud.githubusercontent.com/assets/17786783/14185873/007212ac-f77c-11e5-92a8-66ca7571bf12.png)

**Comment by stechy1** [comment]
To vypadá slibně

**Comment by Zuzacek** [comment]
![ulozitvse1](https://cloud.githubusercontent.com/assets/17786783/14185969/6b65a84e-f77c-11e5-9422-05b8c88bf002.png)

**Comment by Zuzacek** [comment]
Takhle to bude lepší, tamto nebyla úplně černá

**Comment by Vrbikk** [comment]
hotovo
