### ISSUE TITLE
Inicializovat rozvržení BCI t-VEP

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#86]
![img_20160402_095220_hdr](https://cloud.githubusercontent.com/assets/13770080/14225153/d59504e8-f8b8-11e5-9d08-194389f32b05.jpg)

implementování posledního BCI experimentu
- Konfigurační soubor bude obsahovat hodnoty ze screenu "Obecná nastavení" jednou a potom bude obsahovat pole patternů, které mají velikost 1-16 bitů

**Comment by stechy1** [comment]
Je zde malinká chyba. Zjistil jsem problém v pattern kontrolce. Je tam špatná indexace v metodě pro nastavení konkrétního bitu na hodnotu. Chyba je opravena ve větvi s kontrolkou a při mergování bude opravena.

**Comment by Vrbikk** [comment]
implementováno v pořádku
