### ISSUE TITLE
c-VEP, t-VEP tlačítko "uložit hodnoty" lze kliknout i jinde

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#91]
![screenshot_2016-04-02-22-41-37_cz zcu fav tymsnu stimulatorremotecontrol](https://cloud.githubusercontent.com/assets/13770080/14228884/881e1db4-f924-11e5-9a21-b839ed106d78.png)

**Comment by stechy1** [comment]
Tohle je bohužel záměrně. Nevěděl jsem, jak jinak napasovat to tlačítko úplně dolu.

**Comment by Vrbikk** [comment]
ale jinde to je v pohodě ne?

**Comment by stechy1** [comment]
Jenže jinde je nějaké view, které to tlačítko tlačí dolů. Tady nic takového není

**Comment by Vrbikk** [comment]
v tom případě bude lepší to tlačítko vycentrovat a dát zpět nahoru

**Comment by Vrbikk** [comment]
dobrá práce
