### ISSUE TITLE
c-VEP, t-VEP - doplnit popisky

### ISSUE THREAD

**Issue by Vrbikk** [stechy1/stimulatorremotecontrol#94]
c-VEP:
- bitový posun (1-8)
- spinner s počtem výstupů by měl mít větší odsazení od popisovacího labelu 0,5cm na displeji

t-VEP
- pulse lenght [ms]
- čas mezi / time between [ms] až po splnění #92 

společné:
- posuvník jasu by měl vlevo měl mít popisky min a max hodnot na ose "0 -----------------o------------100"
- Brightness [%]

**Comment by stechy1** [comment]
Upravení posuvníku se provede až po zmergování všech větví.

**Comment by Vrbikk** [comment]
tak jo

**Comment by Vrbikk** [comment]
úprava - po domluvě byl změněn vzhled posuvníku bez krajních popisku, ale vpravo od něj bude aktuální hodnota, zdá se mi to u jasu jako lepší řešení

**Comment by stechy1** [comment]
Změna vzhledu posuvníku se projeví až po #96, kde se budou mergovat featury

**Comment by Vrbikk** [comment]
v pořádku
